backend = "etcd"
confdir = "/etc/confd"
debug = true
interval = 300
nodes = [
  "http://10.1.42.1:4001",
]
noop = false
prefix = "/"
quiet = false
scheme = "http"
srv_domain = ""
verbose = true
watch = true
